# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import url_shortener_pb2 as url__shortener__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in url_shortener_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class URLShortenerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/urlshortener.URLShortenerService/Login',
                request_serializer=url__shortener__pb2.LoginRequest.SerializeToString,
                response_deserializer=url__shortener__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetUserUrls = channel.unary_unary(
                '/urlshortener.URLShortenerService/GetUserUrls',
                request_serializer=url__shortener__pb2.UserRequest.SerializeToString,
                response_deserializer=url__shortener__pb2.UserUrlsResponse.FromString,
                _registered_method=True)
        self.CreateShortUrl = channel.unary_unary(
                '/urlshortener.URLShortenerService/CreateShortUrl',
                request_serializer=url__shortener__pb2.CreateUrlRequest.SerializeToString,
                response_deserializer=url__shortener__pb2.ShortUrlResponse.FromString,
                _registered_method=True)
        self.GetUrlAnalytics = channel.unary_unary(
                '/urlshortener.URLShortenerService/GetUrlAnalytics',
                request_serializer=url__shortener__pb2.UrlAnalyticsRequest.SerializeToString,
                response_deserializer=url__shortener__pb2.UrlAnalyticsResponse.FromString,
                _registered_method=True)


class URLShortenerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateShortUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUrlAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_URLShortenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=url__shortener__pb2.LoginRequest.FromString,
                    response_serializer=url__shortener__pb2.LoginResponse.SerializeToString,
            ),
            'GetUserUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserUrls,
                    request_deserializer=url__shortener__pb2.UserRequest.FromString,
                    response_serializer=url__shortener__pb2.UserUrlsResponse.SerializeToString,
            ),
            'CreateShortUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShortUrl,
                    request_deserializer=url__shortener__pb2.CreateUrlRequest.FromString,
                    response_serializer=url__shortener__pb2.ShortUrlResponse.SerializeToString,
            ),
            'GetUrlAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUrlAnalytics,
                    request_deserializer=url__shortener__pb2.UrlAnalyticsRequest.FromString,
                    response_serializer=url__shortener__pb2.UrlAnalyticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'urlshortener.URLShortenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('urlshortener.URLShortenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class URLShortenerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urlshortener.URLShortenerService/Login',
            url__shortener__pb2.LoginRequest.SerializeToString,
            url__shortener__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urlshortener.URLShortenerService/GetUserUrls',
            url__shortener__pb2.UserRequest.SerializeToString,
            url__shortener__pb2.UserUrlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateShortUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urlshortener.URLShortenerService/CreateShortUrl',
            url__shortener__pb2.CreateUrlRequest.SerializeToString,
            url__shortener__pb2.ShortUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUrlAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urlshortener.URLShortenerService/GetUrlAnalytics',
            url__shortener__pb2.UrlAnalyticsRequest.SerializeToString,
            url__shortener__pb2.UrlAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
